$(document).ready(function(){
    
    $('.carousel').carousel({hAlign:'center', 
                            vAlign:'center', 
                            hMargin:0.56, 
                            vMargin:0.4, 
                            frontWidth:360, 
                            frontHeight:500, 
                            carouselWidth:930, 
                            carouselHeight:330, 
                            left:0, 
                            right:0, 
                            top:0, 
                            bottom:0, 
                            backZoom:0.8, 
                            slidesPerScroll:7, 
                            speed:500, 
                            buttonNav:'none', 
                            directionNav:true,
                            autoplay:true, 
                            autoplayInterval:3000, 
                            pauseOnHover:true, 
                            mouse:true, 
                            shadow:true, 
                            reflection:false, 
                            reflectionHeight:0.2, 
                            reflectionOpacity:0.5, 
                            reflectionColor:'0,0,0',
                            description:false, descriptionContainer:'.description',
                            backOpacity:1,
                            before: function(carousel){}, 
                            after: function(carousel){}
                            });
                            
});